#  .::::::.:::::::::::::::.    :::::::..   .::::::.   ::   .:  :::::::::::::. 
# ;;;`    `;;;;;;;;'''';;`;;   ;;;;``;;;; ;;;`    `  ,;;   ;;, ;;; `;;;```.;;;
# '[==/[[[[,    [[    ,[[ '[[,  [[[,/[[[' '[==/[[[[,,[[[,,,[[[ [[[  `]]nnn]]' 
#   '''    $    $$   c$$$cc$$$c $$$$$$c     '''    $"$$$"""$$$ $$$   $$$""    
#  88b    dP    88,   888   888,888b "88bo,88b    dP 888   "88o888   888o     
#   "YMmMY"     MMM   YMM   ""` MMMM   "W"  "YMmMY"  MMM    YMMMMM   YMMMb    

format = """
$username\
$directory\
$git_branch\
$cmd_duration\
$line_break\
$character\
"""

[os]
format = "[$symbol]($style)"
style = "bold bg:#7dc4e4 fg:black"
disabled = false

[username]
style_user = 'bold red'
style_root = 'bold red'
format = '[$user]($style) in '
show_always = true
disabled = false

[directory]
format = '[$path]($style) [$read_only]($read_only_style)'
style = "bold fg:#8aadf4"
read_only = '[󰌾] '
read_only_style = 'bold red'
truncation_length = 3
truncation_symbol = '../'
disabled = false

[git_branch]
format = 'on [$symbol$branch]($style) '
style = 'bold italic fg:#a6da95'
symbol = ' '
truncation_length = 4
truncation_symbol = ''
disabled = false

[time]
format = '[$time]($style)'
time_format = '%R'
style = 'bold yellow'
utc_time_offset = '+9'
disabled = false

[character]
format = '$symbol '
success_symbol = "[❯](bold fg:#c6a0f6)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❯](bold yellow)"
disabled = false

[cmd_duration]
min_time = 1000
format = 'took [$duration](blink bold fg:#eed49f)'
disabled = false


[meson]
symbol = "󰔷 "

[nix_shell]
symbol = " "

[package]
symbol = "󰏗 "

[python]
symbol = " "

[rust]
symbol = "󱘗 "

[os.symbols]
Android = " "
Arch = " "
Artix = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
Gentoo = " "
Linux = " "
Macos = " "
Mint = " "
NixOS = " "
openSUSE = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
