#  .::::::.:::::::::::::::.    :::::::..   .::::::.   ::   .:  :::::::::::::. 
# ;;;`    `;;;;;;;;'''';;`;;   ;;;;``;;;; ;;;`    `  ,;;   ;;, ;;; `;;;```.;;;
# '[==/[[[[,    [[    ,[[ '[[,  [[[,/[[[' '[==/[[[[,,[[[,,,[[[ [[[  `]]nnn]]' 
#   '''    $    $$   c$$$cc$$$c $$$$$$c     '''    $"$$$"""$$$ $$$   $$$""    
#  88b    dP    88,   888   888,888b "88bo,88b    dP 888   "88o888   888o     
#   "YMmMY"     MMM   YMM   ""` MMMM   "W"  "YMmMY"  MMM    YMMMMM   YMMMb    

format = """\
$shell\
[](fg:#c6a0f6)\
$username\
[](fg:#c6a0f6) \
 [on](fg:#f5a97f) \
[](fg:green)\
$os\
[](fg:green) \
 [in](fg:#f5a97f) \
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character\
"""
follow_symlinks = true

[time]
format = '[$time]($style) '
time_format = '%R'
style = 'bold yellow'
utc_time_offset = '+9'
disabled = false

[username]
format = '[$user]($style)'
style_user = 'bold bg:#c6a0f6 bold fg:black'
style_root = 'bold red'
show_always = true
disabled = false

[hostname]
ssh_only = false
format = '[@$hostname](bold bg:#c6a0f6 bold fg:black)'
disabled = false

[os]
format = '[$symbol]($style)'
style = "bold fg:black bg:green"
disabled = false

[os.symbols]
Windows = " "
Arch = "arch"

[directory]
format = '[$path]($style) [$read_only]($read_only_style)'
style = "bold yellow"
home_symbol = './ '
read_only = '[󰌾] '
read_only_style = 'bold red'
truncation_length = 3
truncation_symbol = '…/'

[directory.substitutions]
"Документы" = "󰈙 "
"Загрузки" = " "
"Музыка" = " "
"Видео" = " "
"Изображения" = " "
"Рабочий стол" = " "
".config" = " "
".walls" = "󰟾 "

[character]
format = ' $symbol : '
success_symbol = "[](bold fg:#f5bde6)"
error_symbol = "[](red)"
vimcmd_symbol = "[](yellow)"

[git_branch]
format = "[use](fg:#f5a97f) [$symbol$branch]($style) "
symbol = ''
style = "bold fg:#b7bdf8"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[cmd_duration]
min_time = 1000
format = '[at](fg:#f5a97f) [$duration](blink bold fg:#b7bdf8)'

[line_break]
disabled = false
