#  .::::::.:::::::::::::::.    :::::::..   .::::::.   ::   .:  :::::::::::::. 
# ;;;`    `;;;;;;;;'''';;`;;   ;;;;``;;;; ;;;`    `  ,;;   ;;, ;;; `;;;```.;;;
# '[==/[[[[,    [[    ,[[ '[[,  [[[,/[[[' '[==/[[[[,,[[[,,,[[[ [[[  `]]nnn]]' 
#   '''    $    $$   c$$$cc$$$c $$$$$$c     '''    $"$$$"""$$$ $$$   $$$""    
#  88b    dP    88,   888   888,888b "88bo,88b    dP 888   "88o888   888o     
#   "YMmMY"     MMM   YMM   ""` MMMM   "W"  "YMmMY"  MMM    YMMMMM   YMMMb    

format = """
$shell\
$username\
$directory\
$git_branch\
$package\
$cmd_duration\
$line_break\
$character\
"""

[os]
format = "[$symbol]($style)"
style = "bold bg:#7dc4e4 fg:black"
disabled = false

[shell]
fish_indicator = '\[fish\]($style)'
zsh_indicator = '\[zsh\]($style)'
bash_indicator = '\[bash\]($style)'
powershell_indicator = '\[pwsh\]($style)'
tcsh_indicator = '\[tcsh\]($style)'
cmd_indicator = '\[cmd\]($style)'
nu_indicator = '\[nu\]($style)'
unknown_indicator = '\[sh ?\]'
style = 'bold fg:#f5bde6'
disabled = false

[username]
style_user = 'bold red'
style_root = 'bold red'
format = '[$user]($style) in '
show_always = true
disabled = false

[directory]
format = '[$path]($style) [$read_only]($read_only_style)'
style = "bold fg:#8aadf4"
read_only = '[󰌾] '
read_only_style = 'bold red'
home_symbol = '~~'
truncation_length = 3
truncation_symbol = '../'
disabled = false

[git_branch]
format = 'on [$symbol$branch]($style) '
style = 'bold italic fg:#a6da95'
symbol = ' '
truncation_length = 4
truncation_symbol = ''
disabled = false

[package]
format = 'via [󰏗 $version](bold fg:#f5a97f) '

[cmd_duration]
min_time = 1000
format = 'took [$duration](bold fg:#eed49f)'
disabled = false

[time]
format = '[$time]($style)'
time_format = '%R'
style = 'bold yellow'
utc_time_offset = '+9'
disabled = false

[character]
format = '$symbol '
success_symbol = "[❯❯❯](bold green)"
error_symbol = "[❯❯❯](bold red)"
vimcmd_symbol = "[❯❯❯](bold yellow)"
disabled = false


[meson]
symbol = "󰔷 "

[nix_shell]
format = 'via [$symbol$state]($style) '
style = 'bold fg:#91d7e3'
symbol = " "

[python]
format = 'via [$symbol $version]($style) '
style = 'bold fg:#eed49f'
symbol = " "

[rust]
format = 'via [$symbol $numver]($style) '
style = 'bold fg:#ee99a0'
symbol = "󱘗 "

[os.symbols]
Android = " "
Arch = " "
Artix = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
Gentoo = " "
Linux = " "
Macos = " "
Mint = " "
NixOS = " "
openSUSE = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
