theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = true
cursorline = true
auto-completion = true
completion-replace = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator"]
center = ["file-name"]
right = ["selections", "position", "file-type"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"

[keys.normal]
C-s = ":w"
C-S-s = ":w!"
C-q = ":wq"
C-S-q = ":wq!"
C-o = ":o ~/.config/helix/config.toml"
C-v = ":clipboard-paste-after"
C-c = ":yank-join"
