theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = true
cursorline = true
auto-completion = true
completion-replace = true
auto-info = true
auto-pairs = true
true-color = true
color-modes = true

[editor.indent-guides]
render = true
character = "|"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator"]
center = []
right = ["file-type", "separator", "spacer", "position-percentage", "position", "separator", "total-line-numbers"]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[keys.normal]
C-s = ":w"
C-S-s = ":w!"
C-q = ":wq"
C-S-q = ":wq!"
C-o = ":o ~/.config/helix/config.toml"
C-v = ":clipboard-paste-before"
C-c = ":yank-join"
